#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
import re
import textwrap


def method(source: str) -> str:
    return textwrap.indent(textwrap.dedent(source).lstrip(), "    ")


packet_path = Path("repository-packet.json")
packet = json.loads(packet_path.read_text(encoding="utf-8"))
for path in (
    "tests/test_architecture_documentation_consistency.py",
    "tests/test_repository_navigation.py",
):
    if path not in packet["allowed_paths"]:
        packet["allowed_paths"].append(path)
packet_path.write_text(
    json.dumps(packet, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8",
)

architecture_path = Path("tests/test_architecture_documentation_consistency.py")
architecture = architecture_path.read_text(encoding="utf-8")
replacement = method('''
def test_active_packet_is_machine_declared_and_generated(self) -> None:
    self.assertEqual(self.packet["schema_version"], "crm.repository-packet/v1")
    self.assertEqual(self.packet["packet_id"], "repository-step-8")
    self.assertEqual(self.packet["status"], "active")
    self.assertEqual(
        self.packet["baseline"]["sha"],
        "3849e046e45dbf7e398db7cd58e0aeaca508c045",
    )
    self.assertEqual(self.packet["tracking_issues"], [126, 194])
    for path in (
        ".github/workflows/customer-privacy-owner-execution.yml",
        "crates/crm-application-runtime/tests/customer_privacy_owner_execution_postgres.rs",
        "database/migrations/0105_customer_privacy_owner_execution.up.sql",
        "docs/ACTIVE_PACKET.md",
        "repository-packet.json",
        "tests/test_architecture_documentation_consistency.py",
        "tests/test_repository_navigation.py",
    ):
        self.assertIn(path, self.packet["allowed_paths"])
    self.assertIn("Cargo.toml", self.packet["forbidden_paths"])
    self.assertIn("Cargo.lock", self.packet["forbidden_paths"])
    self.assertIn("services/**", self.packet["forbidden_paths"])
    self.assertIn("Customer Privacy Owner Execution CI", self.packet["required_checks"])
    self.assertIn("Rust CI", self.packet["required_checks"])
    self.assertIn("Rust Generated Sync", self.packet["required_checks"])

    self.assertIn("Generated by scripts/generate_repository_navigation.py", self.active_packet)
    self.assertIn("repository-step-8", self.active_packet)
    self.assertIn(self.packet["baseline"]["sha"], self.active_packet)
    self.assertRegex(self.active_packet, r"sha256:[0-9a-f]{64}")
    self.assertIn("orientation only", self.active_packet)

''')
architecture, count = re.subn(
    r"    def test_active_packet_is_machine_declared_and_generated\(self\) -> None:\n.*?(?=        for document in self\.authoritative_status_documents:)",
    replacement,
    architecture,
    count=1,
    flags=re.S,
)
if count != 1:
    raise SystemExit(f"architecture packet method replacement count: {count}")
architecture_path.write_text(architecture, encoding="utf-8")

navigation_path = Path("tests/test_repository_navigation.py")
navigation = navigation_path.read_text(encoding="utf-8")
declaration = method('''
def test_active_packet_declaration_is_valid_and_exact(self) -> None:
    packet = load_packet(ROOT)
    self.assertEqual(packet["packet_id"], "repository-step-8")
    self.assertEqual(packet["status"], "active")
    self.assertEqual(packet["baseline"]["ref"], "main")
    self.assertEqual(
        packet["baseline"]["sha"],
        "3849e046e45dbf7e398db7cd58e0aeaca508c045",
    )
    self.assertEqual(packet["tracking_issues"], [126, 194])
    for path in (
        ".github/workflows/customer-privacy-owner-execution.yml",
        "crates/crm-application-runtime/tests/customer_privacy_owner_execution_postgres.rs",
        "database/migrations/0105_customer_privacy_owner_execution.up.sql",
        "docs/ACTIVE_PACKET.md",
        "repository-packet.json",
        "tests/test_architecture_documentation_consistency.py",
        "tests/test_repository_navigation.py",
    ):
        self.assertIn(path, packet["allowed_paths"])
    self.assertIn("Cargo.lock", packet["forbidden_paths"])
    self.assertIn("Customer Privacy Owner Execution CI", packet["required_checks"])
    self.assertIn(
        "all applicable permanent workflows pass on one unchanged exact head",
        packet["acceptance"],
    )

''')
navigation, count = re.subn(
    r"    def test_active_packet_declaration_is_valid_and_exact\(self\) -> None:\n.*?(?=    def test_affected_scope_workflow_executes_real_packet_check)",
    declaration,
    navigation,
    count=1,
    flags=re.S,
)
if count != 1:
    raise SystemExit(f"navigation declaration replacement count: {count}")

fixture = method('''
def test_packet_check_reports_affected_scope_without_running_git_or_cargo(self) -> None:
    changed_paths = [
        ".github/workflows/customer-privacy-owner-execution.yml",
        "docs/ACTIVE_PACKET.md",
        "repository-packet.json",
        "tests/test_architecture_documentation_consistency.py",
        "tests/test_repository_navigation.py",
    ]
    affected = {
        "head_sha": "b" * 40,
        "changed_paths": changed_paths,
        "affected_packages": [],
        "selected_workflows": [
            {
                "name": "Governance CI",
                "path": ".github/workflows/governance.yml",
                "selected": True,
                "reasons": ["test fixture"],
            }
        ],
    }
    with (
        patch(
            "scripts.repository_navigation._git",
            return_value="3849e046e45dbf7e398db7cd58e0aeaca508c045",
        ),
        patch("scripts.repository_navigation.build_report", return_value=affected),
        patch("scripts.repository_navigation.stale_generated_documents", return_value=[]),
    ):
        report = packet_check(ROOT, "origin/main")
    self.assertTrue(report["ok"])
    self.assertEqual(report["changed_paths"], changed_paths)
    self.assertEqual(report["blockers"], [])
    self.assertEqual(report["selected_workflows"][0]["name"], "Governance CI")

''')
navigation, count = re.subn(
    r"    def test_packet_check_reports_affected_scope_without_running_git_or_cargo\(self\) -> None:\n.*?(?=    def test_repo_parser_exposes_exact_step_5_commands)",
    fixture,
    navigation,
    count=1,
    flags=re.S,
)
if count != 1:
    raise SystemExit(f"navigation fixture replacement count: {count}")
navigation_path.write_text(navigation, encoding="utf-8")
