from __future__ import annotations

from pathlib import Path
import unittest
from unittest.mock import patch

from scripts.repository_navigation import (
    ACTIVE_PACKET_PATH,
    NAVIGATION_SCHEMA,
    REPOSITORY_MAP_PATH,
    NavigationError,
    evaluate_path_policy,
    explain_target,
    generated_documents,
    load_packet,
    packet_check,
    stale_generated_documents,
)
from scripts.repo import build_parser


ROOT = Path(__file__).resolve().parents[1]


class RepositoryNavigationTests(unittest.TestCase):
    def test_active_packet_declaration_is_exact(self) -> None:
        packet = load_packet(ROOT)
        self.assertEqual(packet["schema_version"], "crm.repository-packet/v1")
        self.assertEqual(packet["packet_id"], "repository-step-15-evidence-closure")
        self.assertEqual(packet["status"], "active")
        self.assertEqual(
            packet["baseline"],
            {"ref": "main", "sha": "4a14a5a0bda6d25d27e7c2da7c5f4809fa1efbdf"},
        )
        self.assertEqual(packet["tracking_issues"], [126, 194])
        self.assertEqual(
            set(packet["allowed_paths"]),
            {
                "docs/ACTIVE_PACKET.md",
                "docs/ARCHITECTURE_COMPLEXITY_AND_SCALABILITY_PLAN.md",
                "docs/IMPLEMENTATION_ROADMAP.md",
                "docs/MODULE_CATALOG.md",
                "docs/PHASE8_DELIVERY_PLAN.md",
                "docs/PROJECT_STATUS.md",
                "repository-packet.json",
                "tests/test_architecture_documentation_consistency.py",
                "tests/test_party_tombstone_rebuild_convergence.py",
                "tests/test_repository_navigation.py",
            },
        )
        self.assertEqual(
            packet["required_checks"],
            ["Affected Scope CI", "Complexity Baseline CI", "Rust Generated Sync", "Rust CI"],
        )
        self.assertIn("mark Repository Steps 1 through 15 complete", packet["deliverables"])
        self.assertIn("implement Repository Step 16 worker conformance", packet["non_goals"])

    def test_generated_navigation_is_deterministic_and_current(self) -> None:
        first = generated_documents(ROOT)
        second = generated_documents(ROOT)
        self.assertEqual(first, second)
        self.assertEqual(set(first), {ACTIVE_PACKET_PATH, REPOSITORY_MAP_PATH})
        for content in first.values():
            self.assertIn("Generated by scripts/generate_repository_navigation.py", content)
            self.assertRegex(content, r"source-digest: sha256:[0-9a-f]{64}")
        self.assertIn("repository-step-15-evidence-closure", first[ACTIVE_PACKET_PATH])
        self.assertIn("4a14a5a0bda6d25d27e7c2da7c5f4809fa1efbdf", first[ACTIVE_PACKET_PATH])
        self.assertIn("**Workspace packages:** 112", first[REPOSITORY_MAP_PATH])
        self.assertIn("`crm.customer-privacy`", first[REPOSITORY_MAP_PATH])
        self.assertEqual(stale_generated_documents(ROOT), [])

    def test_module_and_capability_explanations_remain_resolvable(self) -> None:
        module = explain_target(ROOT, "crm.customer-privacy")
        self.assertEqual(module["schema_version"], NAVIGATION_SCHEMA)
        self.assertEqual(module["kind"], "module")
        self.assertEqual(module["version"], "0.3.0")
        coordinates = {capability["coordinate"] for capability in module["capabilities"]}
        self.assertIn("customer_privacy.case.submit@1.0.0", coordinates)
        self.assertIn("customer_privacy.restriction.place@1.0.0", coordinates)
        capability = explain_target(ROOT, "customer_privacy.case.submit@1.0.0")
        self.assertEqual(capability["kind"], "capability")
        self.assertEqual(capability["route"]["classification"], "public_runtime")
        with self.assertRaisesRegex(NavigationError, "unknown module or capability"):
            explain_target(ROOT, "customer_privacy.unknown@1.0.0")

    def test_path_policy_rejects_forbidden_and_unscoped_changes(self) -> None:
        forbidden, disallowed = evaluate_path_policy(
            ["docs/PROJECT_STATUS.md", "proto/crm/customer/v1/customer.proto", "unowned.txt"],
            ["docs/PROJECT_STATUS.md"],
            ["proto/**"],
        )
        self.assertEqual(forbidden, ["proto/crm/customer/v1/customer.proto"])
        self.assertEqual(disallowed, ["unowned.txt"])

    def test_packet_check_uses_exact_planning_baseline(self) -> None:
        packet = load_packet(ROOT)
        workflow_paths = {
            "Affected Scope CI": ".github/workflows/affected-scope.yml",
            "Complexity Baseline CI": ".github/workflows/complexity-baseline.yml",
            "Rust Generated Sync": ".github/workflows/rust-generated-sync.yml",
            "Rust CI": ".github/workflows/rust.yml",
        }
        affected = {
            "head_sha": "b" * 40,
            "changed_paths": packet["allowed_paths"],
            "affected_packages": [],
            "selected_workflows": [
                {
                    "name": name,
                    "path": workflow_paths[name],
                    "selected": True,
                    "reasons": ["Step 15 evidence closure"],
                }
                for name in packet["required_checks"]
            ],
        }
        with (
            patch(
                "scripts.repository_navigation._git",
                return_value="4a14a5a0bda6d25d27e7c2da7c5f4809fa1efbdf",
            ),
            patch("scripts.repository_navigation.build_report", return_value=affected),
            patch("scripts.repository_navigation.stale_generated_documents", return_value=[]),
        ):
            report = packet_check(ROOT, "origin/main")
        self.assertTrue(report["ok"])
        self.assertEqual(report["changed_paths"], packet["allowed_paths"])
        self.assertEqual(report["blockers"], [])

    def test_repository_workflow_and_parser_contracts_remain_intact(self) -> None:
        affected = (ROOT / ".github/workflows/affected-scope.yml").read_text(encoding="utf-8")
        self.assertIn("Validate active repository packet", affected)
        self.assertIn('python scripts/repo.py packet-check --base "${BASE_REF}"', affected)
        generated_sync = (ROOT / ".github/workflows/rust-generated-sync.yml").read_text(encoding="utf-8")
        rust_ci = (ROOT / ".github/workflows/rust.yml").read_text(encoding="utf-8")
        for workflow in (generated_sync, rust_ci):
            self.assertNotIn("cargo generate-lockfile", workflow)
            self.assertIn("cargo metadata --locked --format-version 1 --no-deps", workflow)
            self.assertIn("git diff --exit-code -- Cargo.lock", workflow)
        parser = build_parser()
        explain = parser.parse_args(["explain", "customer_privacy.legal_hold.place@1.0.0", "--json"])
        self.assertEqual(explain.command, "explain")
        packet = parser.parse_args(["packet-check", "--base", "origin/main", "--write-generated"])
        self.assertEqual(packet.command, "packet-check")
        self.assertTrue(packet.write_generated)


if __name__ == "__main__":
    unittest.main()
