from __future__ import annotations

from pathlib import Path
import unittest
from unittest.mock import patch

from scripts.repository_navigation import (
    ACTIVE_PACKET_PATH,
    NAVIGATION_SCHEMA,
    REPOSITORY_MAP_PATH,
    NavigationError,
    evaluate_path_policy,
    explain_target,
    generated_documents,
    load_packet,
    packet_check,
    stale_generated_documents,
)
from scripts.repo import build_parser


ROOT = Path(__file__).resolve().parents[1]


class RepositoryNavigationTests(unittest.TestCase):
    def test_active_packet_declaration_is_exact(self) -> None:
        packet = load_packet(ROOT)
        self.assertEqual(packet["schema_version"], "crm.repository-packet/v1")
        self.assertEqual(
            packet["packet_id"],
            "repository-step-15-crm-api-no-orphan-closure",
        )
        self.assertEqual(packet["status"], "active")
        self.assertEqual(
            packet["baseline"],
            {
                "ref": "main",
                "sha": "1f889a810c82da3d0fee12427eacccbe43613bac",
            },
        )
        self.assertEqual(packet["tracking_issues"], [126, 194])
        self.assertEqual(
            set(packet["allowed_paths"]),
            {
                ".github/workflows/customer-privacy-owner-execution.yml",
                "docs/ACTIVE_PACKET.md",
                "repository-packet.json",
                "services/crm-api/tests/customer_360_privacy_no_orphan_process_e2e.rs",
                "services/crm-api/tests/support.rs",
                "tests/test_architecture_documentation_consistency.py",
                "tests/test_party_tombstone_rebuild_convergence.py",
                "tests/test_repository_navigation.py",
            },
        )
        self.assertEqual(
            packet["required_checks"],
            [
                "Affected Scope CI",
                "Complexity Baseline CI",
                "Rust Generated Sync",
                "Rust CI",
                "Application Runtime CI",
                "Customer Privacy Owner Execution CI",
            ],
        )
        self.assertIn(
            "synchronize final Repository Step 15 acceptance SHAs",
            "\n".join(packet["non_goals"]),
        )
        self.assertIn(
            "create a Party through the public application gateway of a real crm-api process",
            packet["deliverables"],
        )
        self.assertIn(
            "restart the real crm-api binary without bootstrap and wait for its production Customer360BackgroundWorker cycle",
            packet["deliverables"],
        )
        self.assertIn(
            "reuse the existing crm-api process support through a test-only module shim without changing the service manifest or production source",
            packet["deliverables"],
        )

    def test_generated_navigation_is_deterministic_and_current(self) -> None:
        first = generated_documents(ROOT)
        second = generated_documents(ROOT)
        self.assertEqual(first, second)
        self.assertEqual(set(first), {ACTIVE_PACKET_PATH, REPOSITORY_MAP_PATH})
        for content in first.values():
            self.assertIn(
                "Generated by scripts/generate_repository_navigation.py",
                content,
            )
            self.assertRegex(content, r"source-digest: sha256:[0-9a-f]{64}")
        self.assertIn(
            "repository-step-15-crm-api-no-orphan-closure",
            first[ACTIVE_PACKET_PATH],
        )
        self.assertIn(
            "1f889a810c82da3d0fee12427eacccbe43613bac",
            first[ACTIVE_PACKET_PATH],
        )
        self.assertIn("**Workspace packages:** 112", first[REPOSITORY_MAP_PATH])
        self.assertIn("`crm.customer-privacy`", first[REPOSITORY_MAP_PATH])
        self.assertEqual(stale_generated_documents(ROOT), [])

    def test_module_explanation_traces_customer_privacy_owner(self) -> None:
        explanation = explain_target(ROOT, "crm.customer-privacy")
        self.assertEqual(explanation["schema_version"], NAVIGATION_SCHEMA)
        self.assertEqual(explanation["kind"], "module")
        self.assertEqual(explanation["version"], "0.3.0")
        self.assertEqual(explanation["owner"]["team"], "customer-platform")
        coordinates = {
            capability["coordinate"] for capability in explanation["capabilities"]
        }
        self.assertIn("customer_privacy.case.submit@1.0.0", coordinates)
        self.assertIn("customer_privacy.restriction.place@1.0.0", coordinates)
        self.assertIn("customer_privacy.legal_hold.place@1.0.0", coordinates)
        self.assertTrue(explanation["references"])

    def test_capability_explanation_resolves_binding_and_runtime(self) -> None:
        explanation = explain_target(ROOT, "customer_privacy.case.submit@1.0.0")
        self.assertEqual(explanation["kind"], "capability")
        self.assertEqual(explanation["owner_module_id"], "crm.customer-privacy")
        self.assertEqual(explanation["route"]["classification"], "public_runtime")
        self.assertEqual(
            explanation["binding"]["rpc"],
            "crm.customer_privacy.v1.CustomerPrivacyCaseService.SubmitPrivacyCase",
        )

    def test_unknown_explanation_target_fails_closed(self) -> None:
        with self.assertRaisesRegex(NavigationError, "unknown module or capability"):
            explain_target(ROOT, "customer_privacy.unknown@1.0.0")

    def test_path_policy_rejects_forbidden_and_unscoped_changes(self) -> None:
        forbidden, disallowed = evaluate_path_policy(
            [
                "docs/PROJECT_STATUS.md",
                "tests/test_repository_navigation.py",
                "proto/crm/customer/v1/customer.proto",
                "unowned.txt",
            ],
            ["docs/PROJECT_STATUS.md", "tests/test_repository_navigation.py"],
            ["proto/**"],
        )
        self.assertEqual(forbidden, ["proto/crm/customer/v1/customer.proto"])
        self.assertEqual(disallowed, ["unowned.txt"])

    def test_packet_check_uses_exact_planning_baseline(self) -> None:
        packet = load_packet(ROOT)
        changed_paths = packet["allowed_paths"]
        workflow_paths = {
            "Affected Scope CI": ".github/workflows/affected-scope.yml",
            "Complexity Baseline CI": ".github/workflows/complexity-baseline.yml",
            "Rust Generated Sync": ".github/workflows/rust-generated-sync.yml",
            "Rust CI": ".github/workflows/rust.yml",
            "Application Runtime CI": ".github/workflows/application-runtime.yml",
            "Customer Privacy Owner Execution CI": ".github/workflows/customer-privacy-owner-execution.yml",
        }
        affected = {
            "head_sha": "b" * 40,
            "changed_paths": changed_paths,
            "affected_packages": [],
            "selected_workflows": [
                {
                    "name": name,
                    "path": workflow_paths[name],
                    "selected": True,
                    "reasons": ["crm-api Party privacy no-orphan process packet"],
                }
                for name in packet["required_checks"]
            ],
        }
        with (
            patch(
                "scripts.repository_navigation._git",
                return_value="1f889a810c82da3d0fee12427eacccbe43613bac",
            ),
            patch(
                "scripts.repository_navigation.build_report",
                return_value=affected,
            ),
            patch(
                "scripts.repository_navigation.stale_generated_documents",
                return_value=[],
            ),
        ):
            report = packet_check(ROOT, "origin/main")
        self.assertTrue(report["ok"])
        self.assertEqual(report["changed_paths"], changed_paths)
        self.assertEqual(report["blockers"], [])
        self.assertEqual(
            [workflow["name"] for workflow in report["selected_workflows"]],
            packet["required_checks"],
        )

    def test_affected_scope_workflow_executes_real_packet_check(self) -> None:
        workflow = (ROOT / ".github/workflows/affected-scope.yml").read_text(
            encoding="utf-8"
        )
        self.assertIn("Validate active repository packet", workflow)
        self.assertIn(
            'python scripts/repo.py packet-check --base "${BASE_REF}"',
            workflow,
        )
        self.assertLess(
            workflow.index("Validate active repository packet"),
            workflow.index("Run affected structural preflight"),
        )
        self.assertIn("Upload deterministic affected-scope report", workflow)

    def test_rust_workflows_preserve_committed_lockfile(self) -> None:
        generated_sync = (ROOT / ".github/workflows/rust-generated-sync.yml").read_text(
            encoding="utf-8"
        )
        rust_ci = (ROOT / ".github/workflows/rust.yml").read_text(encoding="utf-8")
        for workflow in (generated_sync, rust_ci):
            self.assertNotIn("cargo generate-lockfile", workflow)
            self.assertIn("cargo metadata --locked --format-version 1 --no-deps", workflow)
            self.assertIn("git diff --exit-code -- Cargo.lock", workflow)
        self.assertNotIn("git add Cargo.lock", generated_sync)
        self.assertIn("cargo clippy --locked --workspace", generated_sync)
        self.assertIn("cargo check --locked --workspace", rust_ci)
        self.assertIn("cargo test --locked --workspace", rust_ci)

    def test_step14_permanent_workflow_package_baselines_remain_exact(self) -> None:
        workflow_expectations = {
            ".github/workflows/customer-privacy-approval.yml": (
                'test "${package_count}" = "112"',
                "Verify real crm-api approval process",
                "Repeat approval library and real-process acceptance",
            ),
            ".github/workflows/customer-privacy-discovery.yml": (
                'if [ "${package_count}" != "112" ]; then',
                "Verify discovery packages and production inventory",
                "Reapply and repeat acceptance",
            ),
            ".github/workflows/customer-privacy-planning.yml": (
                'test "${package_count}" = "112"',
                "Verify planning and read packages and production inventory",
                "Reapply and repeat acceptance",
            ),
        }
        for path, markers in workflow_expectations.items():
            workflow = (ROOT / path).read_text(encoding="utf-8")
            with self.subTest(workflow=path):
                for marker in markers:
                    self.assertIn(marker, workflow)
                self.assertNotIn('test "${package_count}" = "113"', workflow)
                self.assertNotIn(
                    'if [ "${package_count}" != "113" ]; then', workflow
                )

    def test_repo_parser_exposes_navigation_commands(self) -> None:
        parser = build_parser()
        explain = parser.parse_args(
            ["explain", "customer_privacy.legal_hold.place@1.0.0", "--json"]
        )
        self.assertEqual(explain.command, "explain")
        self.assertTrue(explain.json)
        packet = parser.parse_args(
            ["packet-check", "--base", "origin/main", "--write-generated"]
        )
        self.assertEqual(packet.command, "packet-check")
        self.assertEqual(packet.base, "origin/main")
        self.assertTrue(packet.write_generated)


if __name__ == "__main__":
    unittest.main()
