from __future__ import annotations

from pathlib import Path
import unittest
from unittest.mock import patch

from scripts.repository_navigation import (
    ACTIVE_PACKET_PATH,
    NAVIGATION_SCHEMA,
    REPOSITORY_MAP_PATH,
    NavigationError,
    evaluate_path_policy,
    explain_target,
    generated_documents,
    load_packet,
    packet_check,
    stale_generated_documents,
)
from scripts.repo import build_parser


ROOT = Path(__file__).resolve().parents[1]


class RepositoryNavigationTests(unittest.TestCase):

    def test_active_step_20a_product_plane_packet_declaration_is_exact(self) -> None:
        packet = load_packet(ROOT)
        self.assertEqual(packet["schema_version"], "crm.repository-packet/v1")
        self.assertEqual(packet["packet_id"], "repository-step-20a-customer-privacy-product-plane")
        self.assertEqual(packet["status"], "active")
        self.assertEqual(
            packet["baseline"],
            {"ref": "main", "sha": "46f5be276cf2935f1940827581b81cf197b87111"},
        )
        self.assertEqual(packet["tracking_issues"], [194, 126])
        self.assertEqual(set(packet["allowed_paths"]), {
                "apps/web/e2e/customer-privacy.spec.ts",
                "apps/web/src/App.tsx",
                "apps/web/src/CustomerPrivacyPage.test.ts",
                "apps/web/src/CustomerPrivacyPage.tsx",
                "apps/web/src/customerPrivacyViewModel.ts",
                "apps/web/src/routes.test.ts",
                "apps/web/src/routes.ts",
                "docs/ACTIVE_PACKET.md",
                "docs/PHASE8A_CUSTOMER_PRIVACY_PRODUCT_PLANE.md",
                "packages/client/src/customerPrivacy.test.ts",
                "packages/client/src/customerPrivacy.ts",
                "packages/client/src/index.ts",
                "repository-packet.json",
                "scripts/run_e2e.sh",
                "services/crm-api/tests/seed_e2e_fixture.rs",
                "tests/test_architecture_documentation_consistency.py",
                "tests/test_repository_navigation.py",
            })
        self.assertEqual(packet["required_checks"], [
                "Affected Scope CI",
                "Complexity Baseline CI",
                "Governance CI",
                "Product Plane CI",
                "Rust Generated Sync",
                "Rust CI",
            ])
        self.assertIn("Product Plane CI", packet["required_checks"])
        self.assertIn("packages/client/src/customerPrivacy.ts", packet["allowed_paths"])
        self.assertIn("apps/web/e2e/customer-privacy.spec.ts", packet["allowed_paths"])
    def test_generated_navigation_is_deterministic_and_current(self) -> None:
        first = generated_documents(ROOT)
        second = generated_documents(ROOT)
        self.assertEqual(first, second)
        self.assertEqual(set(first), {ACTIVE_PACKET_PATH, REPOSITORY_MAP_PATH})
        for content in first.values():
            self.assertIn("Generated by scripts/generate_repository_navigation.py", content)
            self.assertRegex(content, r"source-digest: sha256:[0-9a-f]{64}")
        self.assertIn("repository-step-20a-customer-privacy-product-plane", first[ACTIVE_PACKET_PATH])
        self.assertIn("46f5be276cf2935f1940827581b81cf197b87111", first[ACTIVE_PACKET_PATH])
        self.assertIn("**Workspace packages:** 112", first[REPOSITORY_MAP_PATH])
        self.assertIn("`crm.customer-privacy`", first[REPOSITORY_MAP_PATH])
        self.assertEqual(stale_generated_documents(ROOT), [])
    def test_module_and_capability_explanations_remain_resolvable(self) -> None:
        module = explain_target(ROOT, "crm.customer-privacy")
        self.assertEqual(module["schema_version"], NAVIGATION_SCHEMA)
        self.assertEqual(module["kind"], "module")
        self.assertEqual(module["version"], "0.3.0")
        coordinates = {capability["coordinate"] for capability in module["capabilities"]}
        self.assertIn("customer_privacy.case.submit@1.0.0", coordinates)
        self.assertIn("customer_privacy.restriction.place@1.0.0", coordinates)
        capability = explain_target(ROOT, "customer_privacy.case.submit@1.0.0")
        self.assertEqual(capability["kind"], "capability")
        self.assertEqual(capability["route"]["classification"], "public_runtime")
        with self.assertRaisesRegex(NavigationError, "unknown module or capability"):
            explain_target(ROOT, "customer_privacy.unknown@1.0.0")

    def test_path_policy_rejects_forbidden_and_unscoped_changes(self) -> None:
        forbidden, disallowed = evaluate_path_policy(
            ["docs/PROJECT_STATUS.md", "proto/crm/customer/v1/customer.proto", "unowned.txt"],
            ["docs/PROJECT_STATUS.md"],
            ["proto/**"],
        )
        self.assertEqual(forbidden, ["proto/crm/customer/v1/customer.proto"])
        self.assertEqual(disallowed, ["unowned.txt"])

    def test_packet_check_uses_exact_planning_baseline(self) -> None:
        packet = load_packet(ROOT)
        workflow_paths = {
            "Affected Scope CI": ".github/workflows/affected-scope.yml",
            "Complexity Baseline CI": ".github/workflows/complexity-baseline.yml",
            "Governance CI": ".github/workflows/governance.yml",
            "Product Plane CI": ".github/workflows/product-plane.yml",
            "Rust Generated Sync": ".github/workflows/rust-generated-sync.yml",
            "Rust CI": ".github/workflows/rust.yml",
        }
        affected = {
            "head_sha": "b" * 40,
            "changed_paths": packet["allowed_paths"],
            "affected_packages": [],
            "selected_workflows": [
                {
                    "name": name,
                    "path": workflow_paths[name],
                    "selected": True,
                    "reasons": ["Step 20A product-plane acceptance"],
                }
                for name in packet["required_checks"]
            ],
        }
        with (
            patch("scripts.repository_navigation._git", return_value="46f5be276cf2935f1940827581b81cf197b87111"),
            patch("scripts.repository_navigation.build_report", return_value=affected),
            patch("scripts.repository_navigation.stale_generated_documents", return_value=[]),
        ):
            report = packet_check(ROOT, "origin/main")
        self.assertTrue(report["ok"])
        self.assertEqual(report["changed_paths"], packet["allowed_paths"])
        self.assertEqual(report["blockers"], [])
    def test_repository_workflow_and_parser_contracts_remain_intact(self) -> None:
        affected = (ROOT / ".github/workflows/affected-scope.yml").read_text(
            encoding="utf-8"
        )
        self.assertIn("Validate active repository packet", affected)
        self.assertIn('python scripts/repo.py packet-check --base "${BASE_REF}"', affected)
        generated_sync = (ROOT / ".github/workflows/rust-generated-sync.yml").read_text(
            encoding="utf-8"
        )
        rust_ci = (ROOT / ".github/workflows/rust.yml").read_text(encoding="utf-8")
        for workflow in (generated_sync, rust_ci):
            self.assertNotIn("cargo generate-lockfile", workflow)
            self.assertIn("cargo metadata --locked --format-version 1 --no-deps", workflow)
            self.assertIn("git diff --exit-code -- Cargo.lock", workflow)
        owner_execution = (
            ROOT / ".github/workflows/customer-privacy-owner-execution.yml"
        ).read_text(encoding="utf-8")
        self.assertGreaterEqual(
            owner_execution.count("customer_privacy_owner_execution_ready_postgres"),
            6,
        )
        self.assertIn("Verify clean PostgreSQL ready-work acceptance", owner_execution)
        self.assertIn(
            "Repeat PostgreSQL ready-work acceptance after reapply", owner_execution
        )
        background = (ROOT / "crates/crm-application-runtime/src/background.rs").read_text(
            encoding="utf-8"
        )
        for marker in (
            "CUSTOMER_PRIVACY_OWNER_EXECUTION_WORKER_ID",
            "BackgroundWorkerPhase::new(260)",
            "CustomerPrivacyProductionDependencies",
            "privacy_dependencies.try_into()",
        ):
            self.assertIn(marker, background)
        contract_ci = (ROOT / ".github/workflows/contracts.yml").read_text(
            encoding="utf-8"
        )
        for marker in (
            "tests/test_contract_lifecycle.py",
            "tests/test_contract_lifecycle_preproduction.py",
            "tests/test_contract_lifecycle_transitions.py",
            "tests/test_contract_release_evidence.py",
            "tests/test_contract_retirement_evidence.py",
            "tests/test_contract_telemetry_catalog.py",
            "scripts/contract_lifecycle_preproduction.py",
            "scripts/contract_lifecycle_transitions.py",
            "scripts/contract_release_evidence.py",
            "scripts/contract_retirement_evidence.py",
            "scripts/generate_contract_lifecycle.py",
            "scripts/generate_contract_telemetry_catalog.py",
            "/releases?per_page=100",
            "/tags?per_page=100",
            "/deployments?per_page=100",
            '--base-ref "origin/${BASE_REF}"',
        ):
            self.assertIn(marker, contract_ci)
        governance = (ROOT / ".github/workflows/governance.yml").read_text(
            encoding="utf-8"
        )
        self.assertGreaterEqual(governance.count('"scripts/local_lifecycle.py"'), 2)
        self.assertGreaterEqual(governance.count('"scripts/local_demo.py"'), 2)
        self.assertGreaterEqual(governance.count('"tests/test_local_demo.py"'), 2)
        self.assertGreaterEqual(governance.count('"tests/test_local_lifecycle.py"'), 2)
        self.assertIn("python scripts/repo.py conformance", governance)
        self.assertIn("Run deterministic local demo seed replay and smoke acceptance", governance)
        parser = build_parser()
        explain = parser.parse_args(
            ["explain", "customer_privacy.legal_hold.place@1.0.0", "--json"]
        )
        self.assertEqual(explain.command, "explain")
        packet = parser.parse_args(
            ["packet-check", "--base", "origin/main", "--write-generated"]
        )
        self.assertEqual(packet.command, "packet-check")
        self.assertTrue(packet.write_generated)
        doctor = parser.parse_args(["doctor", "--profile", "bootstrap", "--json"])
        self.assertEqual(doctor.command, "doctor")
        self.assertEqual(doctor.profile, "bootstrap")
        bootstrap = parser.parse_args(["bootstrap", "--dry-run", "--json"])
        self.assertEqual(bootstrap.command, "bootstrap")
        self.assertTrue(bootstrap.dry_run)


if __name__ == "__main__":
    unittest.main()
