[package]
name = "crm-customer-privacy-application"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
crm-application-composition = { path = "../crm-application-composition" }
crm-capability-plan-support = { path = "../crm-capability-plan-support" }
crm-capability-runtime = { path = "../crm-capability-runtime" }
crm-core-data = { path = "../crm-core-data" }
crm-customer-privacy = { path = "../../modules/crm-customer-privacy" }
crm-customer-privacy-capability-adapter = { path = "../crm-customer-privacy-capability-adapter" }
crm-customer-privacy-cancel-capability-adapter = { path = "../crm-customer-privacy-cancel-capability-adapter" }
crm-customer-privacy-persistence-adapter = { path = "../crm-customer-privacy-persistence-adapter" }
crm-customer-privacy-query-adapter = { path = "../crm-customer-privacy-query-adapter" }
crm-customer-privacy-submit-capability-adapter = { path = "../crm-customer-privacy-submit-capability-adapter" }
crm-customer-privacy-subject-capability-adapter = { path = "../crm-customer-privacy-subject-capability-adapter" }
crm-module-sdk = { path = "../crm-module-sdk" }
crm-proto-contracts = { path = "../crm-proto-contracts" }
crm-query-runtime = { path = "../crm-query-runtime" }
prost = { workspace = true }
