use prost::Message;
use prost_types::{DescriptorProto, FileDescriptorSet};
use std::fs;
use std::path::Path;

#[test]
fn generate_contract_hashes() {
    let descriptor_set = FileDescriptorSet::decode(crm_proto_contracts::FILE_DESCRIPTOR_SET)
        .expect("valid descriptor set");

    let mut message_names = Vec::new();
    for file in descriptor_set.file {
        let package = file.package.as_deref().unwrap_or_default();
        collect_message_names(package, &file.message_type, &mut message_names);
    }

    let mut ts_content = String::new();
    ts_content
        .push_str("// @generated by crates/crm-application-runtime/tests/generate_hashes.rs\n");
    ts_content.push_str("// Authoritative contract descriptor hashes. Do not edit manually.\n\n");
    ts_content.push_str("export const CONTRACT_HASHES: Record<string, Uint8Array> = {\n");

    message_names.sort();
    for name in message_names {
        let hash = crm_proto_contracts::message_descriptor_hash(&name);
        let byte_array_str = hash
            .iter()
            .map(|b| b.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        ts_content.push_str(&format!(
            "  \"{}\": new Uint8Array([{}]),\n",
            name, byte_array_str
        ));
    }
    ts_content.push_str("};\n");

    let client_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("packages/client/src/contract_hashes.ts");

    fs::write(&client_path, ts_content).unwrap();
    println!("Generated contract hashes at {:?}", client_path);
}

fn collect_message_names(prefix: &str, messages: &[DescriptorProto], output: &mut Vec<String>) {
    for message in messages {
        let name = message.name.as_deref().expect("message descriptor name");
        let full_name = if prefix.is_empty() {
            name.to_owned()
        } else {
            format!("{prefix}.{name}")
        };
        output.push(full_name.clone());
        collect_message_names(&full_name, &message.nested_type, output);
    }
}
