// @generated by scripts/generate_contract_telemetry_catalog.py; do not edit.
const DEPRECATED_CONTRACTS: &[(&str, &str, &str, &str, u32)] = &[];
const DEPRECATED_EVENT_DELIVERIES: &[(&str, &str, &str, &str, &str, u32)] = &[];
