// @generated by scripts/generate_contract_telemetry_catalog.py; do not edit.
use crate::contract_usage_telemetry::DeprecatedContractTelemetry;

pub(crate) const DEPRECATED_CONTRACTS: &[DeprecatedContractTelemetry] = &[];
