// @generated by scripts/generate_contract_telemetry_catalog.py; do not edit.
const DEPRECATED_CONTRACTS: &[(&str, &str, &str, &str, u32)] = &[
    (
        "activities.task.create",
        "1.0.0",
        "crm.activities",
        "crm_deprecated_capability_usage_total",
        30,
    ),
];
const DEPRECATED_EVENT_DELIVERIES: &[(&str, &str, &str, &str, &str, u32)] = &[];
