\set ON_ERROR_STOP on

INSERT INTO crm.capability_registry (
  module_id,
  capability_id,
  capability_version,
  contract_version,
  risk,
  is_mutation,
  requires_idempotency,
  requires_approval,
  input_schema_id,
  input_descriptor_hash,
  input_maximum_size_bytes,
  output_schema_id,
  output_descriptor_hash,
  output_maximum_size_bytes,
  authorization_policy_id,
  rate_limit_policy_id,
  compatibility,
  status
)
VALUES
  (
    'crm.customer-enrichment',
    'customer_enrichment.review.seed',
    '1.0.0',
    '1.0.0',
    'medium',
    TRUE,
    TRUE,
    FALSE,
    'crm.customer_enrichment.v1.SuggestionMaterializedEvent',
    decode(repeat('61', 32), 'hex'),
    1048576,
    NULL,
    NULL,
    NULL,
    'customer_enrichment.review.seed',
    NULL,
    'backward',
    'active'
  ),
  (
    'crm.customer-enrichment',
    'customer_enrichment.suggestion.accept',
    '1.0.0',
    '1.0.0',
    'medium',
    TRUE,
    TRUE,
    FALSE,
    'crm.customer_enrichment.v1.AcceptSuggestionRequest',
    decode(repeat('62', 32), 'hex'),
    1048576,
    'crm.customer_enrichment.v1.AcceptSuggestionResponse',
    decode(repeat('63', 32), 'hex'),
    1048576,
    'customer_enrichment.suggestion.accept',
    NULL,
    'backward',
    'active'
  )
ON CONFLICT (module_id, capability_id, capability_version) DO UPDATE
SET contract_version = EXCLUDED.contract_version,
    risk = EXCLUDED.risk,
    is_mutation = EXCLUDED.is_mutation,
    requires_idempotency = EXCLUDED.requires_idempotency,
    requires_approval = EXCLUDED.requires_approval,
    input_schema_id = EXCLUDED.input_schema_id,
    input_descriptor_hash = EXCLUDED.input_descriptor_hash,
    input_maximum_size_bytes = EXCLUDED.input_maximum_size_bytes,
    output_schema_id = EXCLUDED.output_schema_id,
    output_descriptor_hash = EXCLUDED.output_descriptor_hash,
    output_maximum_size_bytes = EXCLUDED.output_maximum_size_bytes,
    authorization_policy_id = EXCLUDED.authorization_policy_id,
    rate_limit_policy_id = EXCLUDED.rate_limit_policy_id,
    compatibility = EXCLUDED.compatibility,
    status = EXCLUDED.status,
    updated_at = clock_timestamp();
