#!/usr/bin/env python3
# One-shot branch-local patch helper; deleted before prerequisite acceptance.
from pathlib import Path

path = Path("tests/test_architecture_documentation_consistency.py")
text = path.read_text(encoding="utf-8")
start_marker = "    def test_active_packet_is_machine_declared_and_generated(self) -> None:\n"
end_marker = "    def test_repository_map_matches_authoritative_inventory(self) -> None:\n"
start = text.index(start_marker)
end = text.index(end_marker, start)
replacement = '''    def test_active_packet_is_machine_declared_and_generated(self) -> None:
        self.assertEqual(self.packet["schema_version"], "crm.repository-packet/v1")
        self.assertEqual(
            self.packet["packet_id"],
            "repository-step-6-generated-sync-prerequisite",
        )
        self.assertEqual(self.packet["status"], "active")
        self.assertEqual(
            self.packet["baseline"]["sha"],
            "59ab9242a5d38aa143313c120d3e076adad9b851",
        )
        self.assertEqual(self.packet["tracking_issues"], [194, 231])
        self.assertIn(
            ".github/workflows/rust-generated-sync.yml",
            self.packet["allowed_paths"],
        )
        self.assertIn(".github/workflows/rust.yml", self.packet["allowed_paths"])
        self.assertIn("docs/ACTIVE_PACKET.md", self.packet["allowed_paths"])
        self.assertIn(
            "tests/test_architecture_documentation_consistency.py",
            self.packet["allowed_paths"],
        )
        self.assertIn("tests/test_repository_navigation.py", self.packet["allowed_paths"])
        self.assertIn("Cargo.lock", self.packet["forbidden_paths"])
        self.assertIn("Cargo.toml", self.packet["forbidden_paths"])
        self.assertIn("contracts/**", self.packet["forbidden_paths"])
        self.assertIn("crates/**", self.packet["forbidden_paths"])
        self.assertIn("database/**", self.packet["forbidden_paths"])
        self.assertIn("Rust CI", self.packet["required_checks"])
        self.assertIn("Rust Generated Sync", self.packet["required_checks"])

        self.assertIn("Generated by scripts/generate_repository_navigation.py", self.active_packet)
        self.assertIn("crm.repository-navigation/v1", self.active_packet)
        self.assertIn(
            "repository-step-6-generated-sync-prerequisite",
            self.active_packet,
        )
        self.assertIn(self.packet["baseline"]["sha"], self.active_packet)
        self.assertRegex(self.active_packet, r"sha256:[0-9a-f]{64}")
        self.assertIn("orientation only", self.active_packet)

'''
updated = text[:start] + replacement + text[end:]
if updated == text:
    raise SystemExit("active packet consistency guard was already current")
path.write_text(updated, encoding="utf-8")
