[package]
name = "crm-customer-privacy-postgres"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
crm-customer-privacy-capability-composition = { path = "../crm-customer-privacy-capability-composition" }
crm-customer-privacy-persistence-adapter = { path = "../crm-customer-privacy-persistence-adapter" }
