[package]
name = "crm-customer-accounts-capability-composition"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
crm-application-composition = { path = "../crm-application-composition" }
crm-capability-runtime = { path = "../crm-capability-runtime" }
crm-core-data = { path = "../crm-core-data" }
crm-customer-accounts-capability-adapter = { path = "../crm-customer-accounts-capability-adapter" }
crm-customer-accounts-query-adapter = { path = "../crm-customer-accounts-query-adapter" }
crm-module-sdk = { path = "../crm-module-sdk" }
crm-party-reference-composition = { path = "../crm-party-reference-composition" }
crm-query-runtime = { path = "../crm-query-runtime" }
